name: Snake Game

on:
  schedule:
    - cron: "0 */5 * * *"  # Atualiza a cada 5 horas
  workflow_dispatch:  # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Faz o checkout do repositório
      - uses: actions/checkout@v3

      # Gera os arquivos do Snake Game
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: vinicioolivindo  # Substitua pelo seu nome de usuário
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Configura o Git e faz commit/push para a branch output
       - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist
          git commit -m "Atualizando animação Snake Game"
          git push origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

